### PR TITLE
Large refactor and proposals for Protocols and base classes

### PR DESCRIPTION
**Pull request by wrongu**
Following up on some live discussions with @bob-carpenter, @jsoules, and @roualdes, the point of this PR is to try to standardize aspects of bayes kit with a common set of protocols and base classes. It reflects my understanding of what's considered good pythonic design, making heavy use of `Protocol`s to define interfaces and `pydantic` to define data classes. This is not complete, but it is already a very big set of changes, and I wanted to kick off a conversation before going any further.

### At a glance

The first thing to look at is the new `bayes_kit.types` module, especially the protocols in `bayes_kit.types.inference`. My primary idea is to separate out types for an __approximation to a distribution__ and types for __inference algorithms__ that construct those approximations. Zooming way out, the inference protocols look like

```python
StepType = TypeVar("StepType")

class DistributionApproximation(Protocol[StepType]):
    def update(self, step: StepType):
        ...
    def draw(self, n: int) -> WeightedSamples:
        ...

class InferenceAlgorithm(Protocol[StepType]):
    model: Optional[LogDensityModel]
    def step(self) -> tuple[StepType, ExtrasType]:
        ...

class InferenceRunner(Protocol[StepType]):
    algorithm: InferenceAlgorithm[StepType]
    approximation: DistributionApproximation[StepType]
```

Note that `StepType` is just a placeholder for an arbitrary other type. In C++ this would be more like `DistributionApproximation<T>` and `InferenceAlgorithm<T>`. The `Runner` is just typed in a way that it insists that `T` is the same for its `algorithm` and `approximation`. 

So, a `DistributionApproximation` is just some class that supports drawing (weighted) samples from it and that can be `update`d. And an `InferenceAlgorithm` is just some class that has a `model` and provides those updates on every `step`. What exactly those steps and updates look like is entirely up to specific implementations. Decoupling the approximation from the inference this way, and gluing them back together in a `Runner`, allows for arbitrary inference algorithms (MCMC, SMC, VI, etc) and approximation types (set of samples, set of chains, variational parameters, etc), while still enforcing some basic iterative structure (`step()` then `update()`).

### Major changes

- new protocols for inference in `bayes_kit.types.inference` (see above)
    - example `BaseMCMC` class with some default behaviors implemented, such as checking size of `init` and handling the `rng`
- new protocols for saving/loading state and automatically generating CLI in `bayes_kit.types.interface`
    - the `HasState` protocol ensures an object can be snapshotted, saved, and restored for repeatable results. All `InferenceAlgorithm`s and `DistributionApproximation`s should implement the `HasState` protocol, but I opted not to enforce this strictly at the protocol level (but note that it is enforced in `BaseMCMC`)
    - the `InitFromParams` protocol sets up easy CLI integration later (but this is still to-do)
- fixed a bug (or at least unexpected behavior) in Metropolis by taking ownership of rng state that was previously inside of the `proposal_fn`

### Still to-do

- be compatible with python 3.9
- use the `step` and `update` interface in tests
- demonstrate how other algorithms that don't conform to `BaseMCMC` fit in to these patterns, like SMC, ADVI, multi-chain MCMC, etc.
- implement CLI to show off why `pydantic` and `pydantic-cli` are useful here
- add default behaviors for `HasState` and merge with `Params`; in principle implementation classes don't need to worry about setting/getting state.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Hi, @wrongu.  Thanks for submitting.  And please take these as my personal opinions.  I haven't asked anyone else on the project what they think. 

I'm afraid we may have very different philosophies about interfaces.  When I see abstractions like `State` and `Params` and `StepType` and `ExtrasType`, I want to see them saving me work, not just grouping things together.   I'm not sure what the motivation was here, even after reading the above description.

Why did you assign HMC both a name and a short name?   Are you imagining some kind of meta framework accessing these things generically?  I'd rather let the user do whatever naming they want on the outside.

I think doc comments should be an absolute last resort, so I'd get rid of comments that just state what the code's doing like `# Declare the model subtype to make type checkers happy`.

What is `inference.py` supposed to be doing for us?  It adds things like `StepType` with this code doc:

```
# StepType is a generic placeholder type that stands for "whatever the intermediate
# outputs of the inference algorithm are" from each call to step(), which are then fed
# to a DistributionApproximation.update() method.
```

This is exactly the kind of thing I was trying to say I was uncomfortable with when we met in person.

The following note, which presumably existed before this PR, hints at the kinds of problems one runs into when trying to shoehorn samplers into frameworks:

```
# Note: MALA is an instance of a Metropolis-Hastings algorithm, but we do not
# implement it here as a subclass in order to cache gradient calls.
```

MALA is also an instance of HMC with one step, but we don't subclass that either, as a direct implementation is cleaner and more efficient.

I don't see how trying to unify SMC (which isn't an MCMC algorithm) and MCMC.  They both make steps, but they're very different. In SMC, the intermediates are multiple copies of the parameters and not themselves draws---only the final step produces draws from the posterior.  So I just don't see how to use all this stuff from the top in an easy way other than to run it and collect samples.  SMC also needs different posterior analysis tools that look at importance weights rather than autocorrelations in Markov chains.  

Rather than trying to do things like building something that checks the init is the right size in MCMC, I'd just provide utility functions that are easily used across samplers.  It's much more flexible to use composition rather than inheritance, though obviously not as automatic in cases where inheritance can be made to work.

I understand that saving/loading state is important if you have runs that might take days.  I don't think it's a priority for this package and it seems like an awful lot of work to try to manage it.  General serialization is hard and I worry this also won't be extensible.

P.S.  Conditions like `np.any(v <= 0)` should be `!np.all(v > 0)` to handle the NaN case appropriately.

**Comment by bob-carpenter** [comment]
> fixed a bug (or at least unexpected behavior) in Metropolis by taking ownership of rng state that was previously inside of the proposal_fn

If there's a simple fix for that, we should pull that out and merge it.

**Comment by jsoules** [comment]
> > fixed a bug (or at least unexpected behavior) in Metropolis by taking ownership of rng state that was previously inside of the proposal_fn
>
> If there's a simple fix for that, we should pull that out and merge it.

We should chat a bit more about whether this is a bug. My understanding was that in the modal case, this isn't code we own (or even necessarily Python code), such that it wouldn't be appropriate to assume that we should be managing the caller's prng state. I.e. I think the proposal function was meant to be factory-sealed, no user-serviceable parts inside.

I agree it's annoying not to have direct access to the rng internals (my memory is fuzzy, but I recall writing tests for this was a real pain); but doing otherwise imposes pretty strong assumptions on the valid inputs. I see three possibilities:
- require caller to give us a class/something stateful that can be seeded & for which we can check/flag if it's been seeded or not; or
- we own all prng generation (for consistency's sake, this probably means users need to write any randomness-dependent function so that it assumes we are the source of truth for the next rand, which may not mesh well with the code they're trying to experiment with); or
- as above, but caller has the option to give us a prng of some kind which we then pass along to the proposal function at every call.

None of those seem super appealing, as they involve breaking the separation between the library user's code (which controls behavior at each step) and the library's own behavior (implementing the larger algorithmic context).

The goal of having this be deterministic is (presumably) for testing; I think for those cases we are okay to have the test caller pass a proposal function which is closed over its seed at a higher level. (It's possible I'm missing a reason that solution isn't sufficient; if so, please let me know.)

**Comment by wrongu** [comment]
@bob-carpenter 

> When I see abstractions like State and Params and StepType and ExtrasType, I want to see them saving me work, not just grouping things together. I'm not sure what the motivation was here, even after reading the above description.

I didn't motivate it well in the PR. Where such abstractions will shine is in the follow-up where we are then able to do things like write a single "runner" that never needs to know details about the algorithm or approximation.

- the point of `State` and the `HasState` interface is to make all algorithms able to save/load state and "pick up where they left off"
- the point of `Params` is to make designing a CLI 10x easier in the future
- I would want to consider merging `State` and `Params` into a single thing later on, but that is something to talk with you all about

> Why did you assign HMC both a name and a short name?

Not sure what you mean by `name`, but the `short_name` is part of the same interface as `Params` and is there for the (eventual) feature of naming algorithms from the command line, like `python run.py --algo=HMCDiag` etc. I'm thinking now that I should remove CLI-related things from this PR. It's unfinished and making it unwieldy.

> I think doc comments should be an absolute last resort, so I'd get rid of comments that just state what the code's doing

Some difference of philosophy here, but happy to defer to your chosen style once all content issues are sorted.

> What is inference.py supposed to be doing for us? ... This is exactly the kind of thing I was trying to say I was uncomfortable with when we met in person.

Apologies if this PR came across as seditious! Just trying to "show" rather than "tell" my design ideas and to keep the conversation going.

My immediate design goal is to make a plug-and-play interface for various algorithms by generalizing a common (highly generic) interface for them. My indirect goal is to share some of what I've been learning about python typing with all of you. As we discussed, I am primarily motivated by research-oriented / pedagogical concerns, since that's where I see BayesKit as having an edge on other frameworks. If/when performance becomes an issue, it won't be due to the protocols.

Perhaps it's a misnomer, but `StepType` is (I think) doing what you want in the sense that it prescribes no type at all. The only real interface *commitment* here is that an inference algorithm should have a `step()` function and the output of this function should be used to `update()` some approximation. Beyond that, the pieces are super flexible. I could spec out what this looks like for SMC and ADVI if that would help, but I wanted to get feeback from you all first.

> ... MALA is also an instance of HMC with one step, but we don't subclass that either

Indeed, I've respected the existing "flat" hierarchy of the four MCMC algorithms you already have. I think that is a good choice (as in the classic Square/Rectangle class design problem). To be explicit, the class hierarchy 

```
InferenceAlgorithm(Protocol)
    - BaseMCMC(Abstract Base Class)
        - HMCDiag
        - MALA
        - MetropolisHastings
            - Metropolis
    - SMC (still to do)
    - ADVI (still to do)
```

...and, of course, this leaves room to pull out something like `BaseSMC` or `BaseVI` in the future.

Hopefully this does not feel like "shoehorning" algorithms into each others frameworks? I agree that is the opposite of what I am trying to do here. If there exists an inference algorithm that cannot be expressed as a series of `step()` and `update()` calls, then my Protocols are in big trouble.

> I don't see how trying to unify SMC (which isn't an MCMC algorithm) and MCMC. They both make steps, but they're very different. 

Agreed – they would have no shared base class (see above), just the shared `step/update` protocols, which is a very minimal commitment. The advantage of writing SMC in separate `step/update` terms is that it provides convenient hooks for the caller to save intermediate progress. For instance, you may be running SMC with 10000 steps, and want to save out intermediate results every 1000 steps. My protocols achieve this by allowing the caller to use `save(smc.get_state())` after a batch of calls to `step/update`.

> Rather than trying to do things like building something that checks the init is the right size in MCMC, I'd just provide utility functions that are easily used across samplers.

Yes, point taken. This felt inelegant when I wrote it, especially anticipating that the same checks would need to be done in VI and SMC. Same goes for the many steps involved in handling seed->rng. I'll plan on pulling these out as utility functions.

> I understand that saving/loading state is important if you have runs that might take days. I don't think it's a priority for this package and it seems like an awful lot of work to try to manage it. General serialization is hard and I worry this also won't be extensible.

Ok, interesting. At least _optional_ serialization of intermediate state was another one of my big design goals here. On the bright side, using the interfaces I have here with pydantic models makes 90% of the serialization cases easy. And on my to-do list (if you all wanted) would be to put State and command line arguments and checks-on-parameters all in one place for each model, making it as-easy-as-possible for future algorithms to include this kind of serialization functionality. On the less-bright side, you're right that it's not 100%. For instance, I don't serialize the proposal and transition functions in metropolis.

FWIW, my current design does not require all classes satisfying the `InferenceAlgorithm` protocol to also satisfy the `HasState` protocol, so it's more of an opt-in feature as written. (That said, I did put it in `BaseMCMC`, which may have been a mistake)

@jsoules 

> We should chat a bit more about whether this is a bug.

Well... it is a failing test I wrote where I asserted I could save and restore state and get identical results. It failed because the proposal rng state wasn't saved/restored. Concerning case (to me) is running from seed for 3 days but it fails on the first day and you restart from a checkpoint. Expected behavior (to me) is that running from seed means deterministic results, regardless of interruptions. But (see above) sounds like saving/loading state may not be a primary concern of Bob's.

> My understanding was that in the modal case, this isn't code we own 

I don't see this as an issue because you're already requiring some (external) code to conform to the `ProposalFn = Callable[[Vector], ArrayLike]` format. I changed this to `ProposalFn = Callable[[ArrayType, np.random.Generator], ArrayLike]`, thinking that worst-case a user could accept some nondeterminism and wrap it with `proposal_fn = lambda x, rng: actual_proposal_fn(x)`. Best-case, they actually make use of the `rng` and get deterministic behavior out. This feels like it should be the documented/expected behavior to me: if you want reproducibility, use the rng we give you. (IIRC similar rng handling by the user is standard in Jax)

**Comment by bob-carpenter** [comment]
I was just about to write that I should have backed up and asked what the motivation for all this is, so thanks for more on that.  Do you think it'd be worthwhile to hop on another Zoom meeting?

I should have emphasized up front that one of the reasons I was doing the development of both this package and BridgeStan outside of Stan is to have more control.  Historically, I'm still smarting from losing the design battle over CmdStan to a framework-oriented design which I find hard to use on the client side and hard to extend on the dev side.  Its promise was automation of command-line interfaces and testing, but I don't think it has worked out well.  At the time of that design, I was still getting over working with J2EE, which is a Java web framework that was very popular in 00s; it was very "pluggable" and hence very config heavy.

Although step and update may seem simple, all these abstractions and things to think about in terms of what's required and what's optional add up.

Let me try to go on a bit about why I'm so skeptical.  Let's look at the simple things we have in play so far.

* Simple MCMC like Metropolis or HMC holds a single value of the parameters in the model's space and updates them serially
*  Ensemble MCMC methods hold multiple copies of parameters and update them one at a time in a nested loop (which can be asynchronous) 
* SMC methods hold multiple copies of parameters, but update them all at once.  The intermediate values in SMC are not intermediate draws---you have to wait for the end and get your draws all at once.  Any kind of posterior analysis like ESS is different (though plugging in draws to estimate expectations is the same---it's the errors on them that are different).
* Simple variational methods like ADVI iterate, but they iterate by updating the approximating family parameters, not the MCMC parameters.  Then when they're done with those iterations, they can generate draws in parallel.

This makes things look relatively heterogeneous, but still simple.  But take a couple more complex cases:

* Stan divides the iterations into a warmup phase and a sampling phase (you might independently specify burn-in, too).  And then Stan divides warmup into three phases (first a basic step size, then a metric adaptation, then a final step size tuning).  There are 5 different things that might need to get serialized depending on where you are at in sampling (the 5th is because the metric adaptation phase of warmup is itself multi-phase and has different things to save between and within blocks).  In all phases, it saves the state of a dual-averaging estimator that estimates step size.  And you need to be able to restart in the right phase.  

* Pathfinder (our new VI algorithm) runs L-BFGS iteratively over the parameter space of the original model.  Then it fires off a bunch of parallel jobs to evaluate the ELBO at each point along the optimization trajectory (using the negation of the L-BFGS estimated inverse Hessian as low-rank plus diagonal covariance). Then, it takes the best approximation, samples from its normal approximation in parallel, then importance resamples serially.  Then we have multi-path Pathfinder which runs 20 copies of Pathfinder in parallel and importance resamples all of the results.

Does that leave Stan and Pathfinder out of the simple framework?  If so, why build it?  If not, how much work is it going to be to make it compatible?  The only abstraction that I see being workable across Monte Carlo methods is "give me N draws".  But even that runs afoul of things like control variates, because now you don't get posterior draws, just other parameter values that when included with draws give you tighter estimators for certain quantities (which varies by what is being estimated).

In contrast, I am 100% behind building reusable low-level tools.  

Before putting much more effort into this, I would suggest you wait and see if we can arrive at any common ground.

P.S.  I had to look up the square/rectangle design quiz.  It's called the "[circle-ellipse problem](https://en.wikipedia.org/wiki/Circle–ellipse_problem)" on Wikipedia.  It's based on the underlying rectangle class being mutable independently in width and height!  That changes everything, which they get to near the end under "[Challenge the premise of the problem](https://en.wikipedia.org/wiki/Circle–ellipse_problem#Challenge_the_premise_of_the_problem)".  If the rectangle has mutable width and height, then square can't inherit from it because a mutable square is *not* a mutable rectangle.

**Comment by wrongu** [comment]
> It's much more flexible to use composition rather than inheritance
> ...
> I am 100% behind building reusable low-level tools.

Thanks for the thorough replies. I am coming around to your way of looking at the design.

Taking a step back and finding common ground, as you say, the three primary _functionalities_ I am hoping to see added to bayes kit are

1. a standard-enough interface for savable/loadable state
2. a standard-enough interface command line tooling
3. better initialization / warmup / tuning procedures such that the various algorithms work decently well out of the box on moderately tricky problems such as those in posteriordb (see #32)

My approach to (1) and (2) was to unify the class designs via inheritance (which I also thought had the side-effect of better pedagogy). But as you point out, shared utility functions can achieve the same thing without coercing things into one framework. I hadn't yet touched (3), which is probably the most important one.

I think it is still valuable to talk about standard protocols for (1) and (2), which I could move to a separate PR without any of the `bayes_kit.types.inference` protocols I added here. Just having a common CLI factory would probably address all of my concerns as someone who wants to compare various algorithms side-by-side, and would avoid the inheritance issues that you're wary of.

So, the open issues as I see them are still:

- how and whether to do CLI tooling (I advocate for some magic pydantic patterns as hinted at in this PR)
- how and whether to do savable/loadable state (could piggy-back on the same pydantic pattern)
- address concerns in #32
- minor: the `proposal_fn` rng ownership issue raised above

These could each be promoted to their own github issue and this PR can be closed.

**Comment by WardBrian** [comment]
Hi @wrongu -

I unfortunately missed the Zoom meeting last week, so forgive me if there are things I ask that were discussed then:

> a standard-enough interface command line tooling

To my knowledge this has never previously been a goal (even nebulously) for bayes-kit. I'm not even sure how this would work, since the model needs to be specified somewhere as Python code.

I would argue something like a CLI should be built on top of bayes-kit, not inside of it. Surely even for comparison, you will be doing that in a scripted way, so using it as a Python library rather than a CLI seems more direct anyway.

> better initialization / warmup / tuning procedures

These are also goals of ours, but in previous discussions we were thinking of these primarily as being separate algorithms than the ones we currently have implemented. In other words, the implementation of e.g. Metropolis-Hastings is "done", it won't receive any of these features, **but**, we will likely have several "Adaptive Metropolis" variants implemented separately from the current, simple, M-H. Similarly, we plan to _add_ an implementation of NUTS, but as an extra option, not a replacement for the already-implemented HMC.

---

Now, on the specifics of this PR itself, my initial reaction is that this goes too far in its abstraction of these things. I could definitely eventually see the need for base classes, but to me the proposed changes here go against some of our explicit goals (e.g. readability/teachability of the algorithms) without benefiting others (speed, etc). Pydantic isn't a huge dependency, granted, but I also don't see it as being a super necessary one.

**Pull request closed without merging**
