### PR TITLE
Fixing 'init or' syntax

### PR DESCRIPTION
**Pull request by wrongu**
Using `self._thetas = init or np.random.normal(...)` fails when `init` is given as a numpy array. This change makes an explicit check for `None` instead.

### CODE REVIEW

**Comment by jsoules** [comment]
Hi! Thanks for your contribution.

I'm a little unclear on the issue that you're responding to, though. Are you referring to the case when the user passes an empty numpy array for the initialization values? As far as I could tell, that was still falling back to random initialization.

Could you add to this PR a unit test that fails under the current design and passes once your changes are incorporated? That would make things much clearer. (Feel free to add a new file under the `test` directory for now, we can move it around if needed.)

**Comment by wrongu** [comment]
I'm referring to the case where the user wants to set `init` equal to a particular (non-empty) numpy array. My use-case is that I am wrapping inference in some logic to save state/resume from saved state to handle cases where compute jobs fail. So, I would like to set `init` equal to the last-saved-sample and continue the chain from there.

Hopefully this illustrates the problem:

```bash
$ python3
>>> import numpy as np
>>> # Case 1: no problem when x is None
>>> x = None
>>> y = x or np.random.randn(3)
>>> y
array([ 0.26367308, -0.71538487, -1.8833259 ])
>>> # Case 2: no problem (but deprecation warning) when x is an empty array
>>> x = np.array([])
>>> y = x or np.random.randn(3)
DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
>>> y
array([-0.35291691, -0.90878518, -1.10514161])
>>> # Case 3: error! expected behavior is that y gets its value from x rather than from randn
>>> x = np.array([1.0, 2.0, 3.0]
>>> y = x or np.random.randn(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

If you think this warrants a unit test, I could maybe write one sometime later.

**Comment by jsoules** [comment]
> Is there something in bayes-kit that fails now? It helps indicate what's failing to have a unit test that fails in the current system. If we don't currently have a unit test that tests init with an array, then we absolutely need one.

Bob, it looks like the issue is that the behavior depends on the number of elements in the numpy array--if it's none, it warns (for now) but does the right thing (and won't in the future). If it's a single element (the case we've tested), it does the right thing. If it's multiple elements, it fails.

So it's not just testing `init` with an array, but with a multi-element one, because the numpy behavior is inconsistent based on value (not just formal type).

While we're looking at this, should we also add a check that the `init` parameter, if passed, has the right shape?

**Comment by bob-carpenter** [comment]
Got it.  Yes, I think we should also check that `init` is the right shape as soon as we can and provide a meaningful error.  We should probably be thinking about sharing these tests across samplers.  I plan to start working on some new partial momentum refresh MALA-type samplers this week.

**Comment by jsoules** [comment]
Ok. I'm going to suggest that we merge this as is, and open a separate issue for checking `init` shape & testing same. Is that good? Or do you want a test in this before we merge the PR?

**Comment by bob-carpenter** [comment]
Personally, I always want a test of old behavior failing before submitting a patch.  I'm OK pushing off init checking to a separate PR if that's easier.

**Pull request merged**
