### PR TITLE
Update MALA to use Metropolis-Hastings code

### PR DESCRIPTION
**Pull request by WardBrian**
Closes the second half of #2

I did not literally make MALA a subclass of Metropolis-Hastings, since doing so would require defining the proposal and correction as separate functions which couldn't share work

### CODE REVIEW

**Comment by WardBrian** [comment]
I think that would make the user-facing API much heavier, since instead of a "simple" proposal looking like
```python
proposal_fn = lambda theta: np.random.normal(loc=theta, scale=4)
```
The model now needs to get involved, so the smallest it could be is 

```python
# assume model is defined somewhere
def proposal_fn(theta):
    prop = np.random.normal(loc=theta, scale=4)
    lp = model.log_density(prop) # note: this function is now a closure over model
    return (prop, lp)
```

**Comment by bob-carpenter** [comment]
I thought the point was so that the random variate generator and log density evaluation is done so as to share code.  I think that requires just delegating this call to the model.  On the other hand, I don't see what code sharing you expect here other than using the output of the RNG as input to the log density.

**Comment by WardBrian** [comment]
Perhaps it's clearer to just write out

You could define MALA like this:
```python
from typing import Optional, Union
from numpy.typing import NDArray
import numpy as np

from .model_types import GradModel
from .metropolis import MetropolisHastings



class MALA(MetropolisHastings):
    def __init__(
        self,
        model: GradModel,
        epsilon: float,
        init: Optional[NDArray[np.float64]] = None,
        seed: Union[None, int, np.random.BitGenerator, np.random.Generator] = None,
    ):
        self._epsilon = epsilon
        super().__init__(
            model,
            proposal_fn=self._proposal,
            transition_lp_fn=self._correction,
            init=init,
            seed=seed,
        )

    def _proposal(self, theta: NDArray[np.float64]) -> NDArray[np.float64]:
        _, grad_theta = self._model.log_density_gradient(theta)
        return (
            theta
            + self._epsilon * grad_theta
            + np.sqrt(2 * self._epsilon) * self._rand.normal(size=self._model.dims())
        )

    def _correction(
        self,
        theta_prime: NDArray[np.float64],
        theta: NDArray[np.float64],
    ) -> float:
        _, grad_theta = self._model.log_density_gradient(theta)
        x = theta_prime - theta - self._epsilon * grad_theta
        dot_self: float = x.dot(x)
        return (-0.25 / self._epsilon) * dot_self
```

(ignoring the fact that MyPy now forgets that `self._model` is broader than just a `LogDensityModel` and complains, this passes all our tests).

The difficulty is in the internals of `MetropolisHastings`. For each call to `sample`:
1. We call `_proposal(theta)` to generate `theta_prop` 
2. We call `_correction(theta_prop, theta)`
3. We call `_correction(theta, theta_prop)`

If you count them up, that means each iteration calls `log_density_gradient` 3 times, twice on `theta` and once on `theta_prop`. 

The current way `MALA` is coded, we only call `log_density_gradient` once per iteration, so it is in theory three times faster than the version where we strictly adhere to the MH API.

**Comment by bob-carpenter** [comment]
Even with the general case, we should only need one log_density_gradient call.  I can't quite tell what `_correction` is doing here, but it shouldn't be continually calling the log_density_gradient function.  Metropolis-Hastings in the dumbest iteration should call each iteration:  

* gradient for proposal
* log density of original and proposed point
* log density of both transitions

So that's only one call to `log_density_gradient` as there's only one gradient required.  I'm assuming that any log_density_gradient implementation also implements just log_density.

**Comment by WardBrian** [comment]
`_correction` computes the Hastings correction for MALA’s proposal, 

`log q(x' | x) = -0.25 * dot_self(x' - x - epsilon * grad(x))`

Feel free to correct me if it’s possible to compute this without the gradient, I’m just following from the formula I’ve seen on line and the current code. The current code only does one gradient call per iteration because it knows what is being re-used.

**Comment by bob-carpenter** [comment]
Thanks.  I keep forgetting that the gradient's needed to figure out where the normal location is for the random part of the proposal.

**Review by bob-carpenter — CHANGES_REQUESTED** [review]
This is really OK, but I have a few questions and comments around general style and organization.

* Why is the MH test in the Metropolis file? 
* We shouldn't call the internal function `_correction` because the actual Hastings correction factor is the ratio of two corrections (or difference on the log scale); these are just log densities from `theta` to `theta_prop` and from `theta_prop` to `theta`
*  I don't like the long variable names for everything as I find it makes it harder for me to read the math;  I can't even guess what the `_al` suffix means for `grad_prob_al` (for the end of "proposal" maybe?) or why there is a `grad_prob_al` and a `grad_prop`;  if you want to distinguish usages, there is `theta` and `theta_prop` so I would find `grad` and `grad_prop` clearer;  I find `_forward` a bit confusing in that it's the proposal log density and in a different measure than the the other log densities, which are of the target; `_rng` is more typical as a name than `_rand`, but I can live with `_rand` if we're consistent
* If there's a copy cost for `np.asannyarray` when gradients are not passed an NDArray, we should document that
* people vary on this, but I'd prefer not to have redundant parens in expressions like `(-0.25 / self._epsilon) * dot_self` as there's a kind of scalar implicature that they're necessary; on the other hand, I'm less sure about efficiency, but `-0.25 * self._epsilon` can be a constant
* in the correction, `dot_self` is the squared distance from proposal to mean
* I generally am on the extreme end of this spectrum, but I don't like all the vertical space in functions like `sample`.  I'd have used no blank lines in that function myself because the names are so verbose
* for the type `Sample`, I would prefer `Draw`;  a sample is a sequence (or more generally multiset) of draws;  this may be inconsistent elsewhere, but I'd like to stick to this more proper terminology rather than using "sample" for the a single draw and for a multiset of draws

**Comment by jsoules** [comment]
> * I don't like the long variable names for everything as I find it makes it harder for me to read the math

This is a point on which I would differ pretty strongly. I find the long variable names make it much easier to follow the author's intention (whether mathematical or algorithmic), especially given notation that's overloaded (so many `alpha`s), paper-specific, or otherwise pretty opaque.

For a similar reason, I do actually favor parentheses for clarity of expression chunking, even if they aren't strictly necessary. (But I won't fight on this point; code is just always going to be an awkward way to write math expressions that involve fractions.)

**Comment by WardBrian** [comment]
>Why is the MH test in the Metropolis file?

#17 the code for both Metropolis and MetropolisHastings in the same file. I think this is probably the right thing to do (in the limit, it doesn't really make sense for every variant of an algorithm to get its own file), but we can argue if said file should have a better name.

> `_correction`

I've renamed it to `_directional_log_density`, let me know if you have a better name for it

>  I can't even guess what the `_al` suffix means for `grad_prob_al` (for the end of "proposal" maybe?)

It stands for `ArrayLike`. This ties in to your next question, but it is basically an implementation detail because of how we defined the Model types. If we wanted to be significantly more restrictive about the types of the model functions we were accepting, we wouldn't need to do this with `asanyarray`. 
If a user does provide something which isn't an ndarray, this will be a non-zero-cost call. I think we need to document that at the top-level of the library, since it will be true for basically all the callbacks a user provides.

That said, it's not really worth requiring the user to do it - they'd just call `np.array()` on their list before passing it to us, which is exactly the same cost.

>  I find `_forward` a bit confusing in that it's the proposal log density and in a different measure than the the other log densities, which are of the target

Happy to change it, but I'm not sure what a better name is.

> _rng is more typical as a name than _rand, but I can live with _rand if we're consistent
Sure, I don't mind saving a character for a better name

> for the type Sample, I would prefer Draw

I like this better, too. I've updated the other couple usages, and in the long term we will want that to live in its own file rather than at the top of each one most likely

**Comment by bob-carpenter** [comment]
> I've renamed it to _directional_log_density, let me know if you have a better name for it

Yes, I do.  Please let me belabor the point.  I would call it `_proposal_lpdf` because it's the PROPOSAL Log Probability Density Function.  I'm not sure if `_proposal_lpdf` seems too terse to you, but the full description `_proposal_conditional_log_probability_density_function` is obviously too verbose.  

Technically, the `_proposal_lpdf` function is the conditional log density of the proposed parameters `theta'` given the current parameters `theta`, i.e., `log q(theta' | theta)`, where we follow the standard Bayesian stats convention of overloading the density function `q` and resolving by argument names (not argument types!).  

MCMC is confusing because there are usually (at least) two measures in play, the measure for proposals and the measure in which the target density lives.  We typically use `q` for proposals and `p` for the target densities.  Things get even more confusing because there are two conditional densities in play, the proposal density and the transition kernel density, where the transition kernel density is typically a mixed continuous/discrete thing because there's a non-zero probability mass at the current parameter value.  Stationarity conditions for Markov chains relate the transition kernel and target density, saying that transitions under the kernel  preserve the target measure.  

Measures assign probabilities to events.  Events are subsets of parameter values.  If `X` is a random variable and `x` is a bound variable, `x <= X` is the event that the value of `X` is greater than or equal to `x`.  The cumulative distribution function for the random variable `X` is `F_X(x) = Pr[x <= X]` in the measure `Pr`.  Then, the density is just `p(x) = d/d.x F_X(x)`, which has units of change in probability.  This is why we never call the value of a pdf a probability---it's the wrong units.

To disambiguate densities, we subscript with random variables and conditioning, e.g., writing `q_{Theta' | Theta}(theta' | theta)` to disambiguate `q(theta' | theta)` if there are multiple random variables in play that might cause confusion.  But usually it's clear because we establish a one-to-one convention of naming bound variables after their capitalized random variable counterparts.

Whew, that took a bit longer than expected, but this stuff really really nagged at me moving into stats from CS, so I hope it helps.

**Comment by WardBrian** [comment]
Is the name `_proposal_log_density` an acceptable compromise for writing out the complete name? Otherwise we can go with `_proposal_lpdf`

**Comment by bob-carpenter** [comment]
I can live with "proposal log density".  "pdf" is standard, but "lpdf" is something we made up for Stan.

**Comment by WardBrian** [comment]
I've just resolved the conflict that merging #20 caused so this should be ready to go now

**Review by bob-carpenter — APPROVED** [review]
looks good.  thanks.

**Pull request merged**
